package de.hft_stuttgart.pro3;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainForm {
    private final MainFrame frame;
    private JPanel panel1;
    private JPanel centralPanel;

    public MainForm(MainFrame frame) {
        this.frame = frame;
        MenuBar menuBar = new MenuBar();
        Menu gameMenu = new Menu("Spiel");
        MenuItem newGame = new MenuItem("Neues Spiel");
        $$$setupUI$$$();
        newGame.addActionListener(actionEvent -> {
            ((SudokuPanel) centralPanel).createSolution();
        });
        gameMenu.add(newGame);
        menuBar.add(gameMenu);
        frame.setMenuBar(menuBar);
        MenuItem endGame = new MenuItem("Und Tschüss!");
    }

    private void createUIComponents() {
        centralPanel = new SudokuPanel(frame);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(centralPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
